library (ape)
install.packages ("ape")
library (ape)
getwd()
setwd("c:/Users/JoJo/Desktop/")
ls
ls()
list.files()
list.files(pattern= "rodent
list.files(pattern= "rodent")
read.tree(rodent.tree)
read.tree("rodent.tree")
tr<- read.tree("rodent.tree")
plot (tr)
plot (tr, use.edge.length=F)
plot (tr,use.edge.length=F,main= "mirandita")
plot (tr,use.edge.length=F,main= "mirandita para rodent.tree con branch lenght equal")
plot (tr,type="p" ,use.edge.length=F,main= "mirandita")
plot (tr,type="c" ,use.edge.length=F,main= "mirandita")
plot (tr,type="u" ,use.edge.length=F,main= "mirandita")
plot (tr,type="r" ,use.edge.length=F,main= "mirandita")
plot (tr,type="f" ,use.edge.length=F,main= "mirandita")
savehistory
savehistory()
savehistory("nocambiare.r")
plot (tr,type="p" ,use.edge.length=F,main= "mirandita",direction= "l")
plot (tr,type="c" ,use.edge.length=F,main= "mirandita",direction= "l")
plot (tr,type="c" ,use.edge.length=F,main= "mirandita cladograma tipo c con equal branch length y voltiao",direction= "l")
plot (tr,type="c" ,use.edge.length=F,main= "mirandita",direction= "l")
plot (tr,type="c" ,use.edge.length=F,main= "mirandita",direction= "l")
plot (tr,type="c" ,use.edge.length=F,main= "mirandita cladograma tipo c con equal branch length y voltiao",direction= "l")
###fig 4.2###
plot (tr,type="c" ,use.edge.length=F,main= "mirandita cladograma tipo c con equal branch length y voltiao",direction= "l")
### fig 4.3###
plot (tr,type="c",use.edge.length=F,main= "mirandita cladograma tipo c con equal branch length y voltiao y justificado",direction= "l",adj=1)
plot (tr,type="c",use.edge.length=F,main= "mirandita cladograma tipo c con equal branch length y voltiao y justificado",direction= "l",adj=02)
plot (tr,type="c",use.edge.length=F,main= "mirandita cladograma tipo c con equal branch length y voltiao y justificado",direction= "l",adj=0)
plot (tr,type="c",use.edge.length=F,main= "mirandita cladograma tipo c con equal branch length y voltiao y justificado",direction= "l",adj=-1)
plot (tr,type="c",use.edge.length=F,main= "mirandita cladograma tipo c con equal branch length y voltiao y justificado",direction= "l",adj=4)
plot (tr,type="c",use.edge.length=F,main= "mirandita cladograma tipo c con equal branch length y voltiao y justificado",direction= "l",adj=0)
###fig 4.4###
plot (tr,type="c",use.edge.length=F,main= "mirandita cladograma tipo c con equal branch length y voltiao y justificado",direction= "l",adj=0,no.margin= T)
plot (tr,type="u",use.edge.length=F,main= "mirandita sin root",direction= "l",adj=0,no.margin= T)
plot (tr,type="u",use.edge.length=F,main= "mirandita sin root",no.margin= T)
plot (tr,type="u",use.edge.length=T,main= "mirandita sin root",no.margin= T)
plot (tr,type="u",use.edge.length=F,main= "mirandita sin root",no.margin= T, font=1)
plot (tr,type="u",use.edge.length=T,main= "mirandita sin root",no.margin= T)
plot (tr,type="u",use.edge.length=T,main= "mirandita sin root",no.margin= T, lab4ut= "radial")
plot (tr,type="u",use.edge.length=T,main= "mirandita sin root",no.margin= T, lab4ut= "horizontal")
plot (tr,type="u",use.edge.length=F,main= "mirandita sin root",direction= "l",adj=0,no.margin= T)
plot (tr,type="u",use.edge.length=T,main= "mirandita sin root",no.margin= T, lab4ut= "horizontal",cex= 0.1)
plot (tr,type="u",use.edge.length=T,main= "mirandita sin root",no.margin= T, lab4ut= "horizontal",cex= 1)
plot (tr,type="u",use.edge.length=T,main= "mirandita sin root",no.margin= T, lab4ut= "horizontal",cex= 0.8,adj= 1)
plot (tr,type="u",use.edge.length=T,main= "mirandita sin root",no.margin= T, lab4ut= "horizontal",cex= 0.8,adj= 0)
plot (tr,type="u",use.edge.length=T,main= "mirandita sin root",no.margin= T, lab4ut= "horizontal",cex= 0.8, label.offset= 1)
plot (tr,type="u",use.edge.length=T,main= "mirandita sin root",no.margin= T, lab4ut= "horizontal",cex= 0.8, label.offset= 0)
###fig 4.5###
plot (tr,type="f",use.edge.length=T,main= "mirandita modo fan")
plot (tr,type="f",use.edge.length=T,main= "mirandita modo fan", srt= 30)
plot (tr,type="f",use.edge.length=T,main= "mirandita modo fan", srt= 0)
plot (tr,type="f",use.edge.length=T,main= "mirandita modo fan")
plot (tr,type="f",use.edge.length=T,main= "mirandita modo fan", no.margin= T)
plot (tr,type="r",use.edge.length=T,main= "mirandita modo fan", no.margin= T)
###fig 4.6###
plot (tr,type="r",use.edge.length=T,main= "mirandita modo fan", no.margin= T)
###fig 4.7###
plot (tr,type="r",use.edge.length=T,main= "mirandita modo fan", nodelabels())
plot (tr,type="c",use.edge.length=T,main= "mirandita modo fan", nodelabels())
plot (tr,type="p",use.edge.length=T,main= "mirandita modo fan", nodelabels())
dev.off()
plot (tr,type="p",use.edge.length=T,main= "mirandita modo fan", nodelabels())
plot (tr,type="p",use.edge.length=T,main= "mirandita modo fan", nodelabels())
plot (tr)
plot (tr); nodelabels (tr$node.label, adj= 0, frame="n")
nodelabels("6.4 Miranditas", 15, frame= "c", bg= "white")
nodelabels("6.4 Miranditas", 15, frame= "c", bg= "white", cex= 0.5)
dev.off()
nodelabels("6.4 Miranditas", 15, frame= "c", bg= "white", cex= 0.5)
plot (tr)
nodelabels("6.4 Miranditas", 15, frame= "c", bg= "white", cex= 0.5)
nodelabels("1.8 Fersitos", 15, frame= "c", bg= "white", cex= 0.5)
nodelabels("1.8 Fersitos", 16, frame= "c", bg= "white", cex= 0.5)
variable <- scan()
?scan
bs.ml <- NA 88 76 73 71 100 45 81 72 67 63 100 100
bs.ml <- c(NA,88, 76, 73, 71, 100, 45, 81, 72, 67, 63, 100, 100)
bs.nj <- c(NA, 74, 48, 68, 75, 100, NA, 91, 67, 82, 52, 100, 100)
bs.pars <- c(NA, 76, 34, 54, 74, 100, 56, 91, 74, 60, 63, 100, 100)
str(bs.pars)
bs.pars <- c("NA", 76, 34, 54, 74, 100, 56, 91, 74, 60, 63, 100, 100)
str(bs.pars)
bs.pars <- c(NA, 76, 34, 54, 74, 100, 56, 91, 74, 60, 63, 100, 100)
str(bs.pars)
dev.off()
plot (tr)
nodelabels(bs.pars)
nodelabels(bs.nj)
nodelabels(bs.ml)
nodelabels(bs.pars, frame="n")
dev.off()
plot(tr)
nodelabels(bs.pars, frame="n")
dev.off()
plot(tr)
nodelabels(bs.pars, adj= c(-0.2,-0.1),frame="n")
nodelabels(bs.pars, adj= c(-0.2,-0.1),frame="n",cex= 0.8, font= 2)
dev.off()
plot(tr)
nodelabels(bs.pars, adj= c(-0.2,-0.1),frame="n",cex= 0.8, font= 2)
nodelabels(bs.pars, adj= c(-0.2,-0.15),frame="n",cex= 0.8, font= 2)
nodelabels(bs.pars, adj= c(-0.2,-0.2),frame="n",cex= 0.8, font= 2)
nodelabels(bs.pars, adj= c(-0.3,-0.2),frame="n",cex= 0.8, font= 2)
nodelabels(bs.pars, adj= c(-1,-0.2),frame="n",cex= 0.8, font= 2)
nodelabels(bs.pars, adj= c(-0.2),frame="n",cex= 0.8, font= 2)
dev.off()
plot(tr)
nodelabels(bs.pars, adj= c(-0.2),frame="n",cex= 0.8, font= 2)
nodelabels(bs.nj, adj(1.2,-0.5), frame="n", cex= 0.8, font= 3)
nodelabels(bs.nj, adj=(1.2,-0.5), frame="n", cex= 0.8, font= 3)
nodelabels(bs.nj, adj=c(1.2,-0.5), frame="n", cex= 0.8, font= 3)
nodelabels(bs.ml, adj=c(1.2,1.5), frame="n", cex= 0.8)
add.scale.bar(length =0.01)
dev.off()
plot(tr)
nodelabels (thermo=bs.ml/100, piecol= "grey")
?nodelabels
nodelabels (thermo=bs.ml/100, piecol= "grey", horiz=0.5)
dev.off()
plot(tr)
nodelabels (thermo=bs.ml/100, piecol= "grey", width=0.5)
dev.off()
plot(tr)
nodelabels (thermo=bs.ml/100, piecol= "grey", horiz=-0.5)
dev.off()
plot(tr)
nodelabels (thermo=bs.ml/100, piecol= "grey", height=-0.5)
dev.off()
plot(tr)
nodelabels (thermo=bs.ml/100, piecol= "grey", height=-0.5, width=0.5)
dev.off()
plot(tr)
nodelabels (thermo=bs.ml/100, piecol= "grey", height=-0.5, width=-0.5)
dev.off()
plot(tr)
nodelabels (thermo=bs.ml/100, piecol= "grey", height=-0.5, horiz=-0.5)
co <- c("black","grey",
co <- c("black","grey","white")
co <- c("black","grey","white")
plot (tr)
p<- character(length(bs.ml))
p
bs.ml >= 90
p[bs.ml >= 90] <- co [1]
p
bs.ml
p[bs.ml <90 & bs.ml >=70] <- col [2]
p[bs.ml <90 & bs.ml >=70] <- co [2]
bs.ml
p
p[bs.ml < 70] <- co [3]
p
p[bs.ml == NA] <- "red"
p
#como se asigna color a un NA tarea#
#### el numero del terminal es el conteo de arriba para abajo###
#### averiguar como conozco el numero del terminal###
### hasta 4.16 sin 4.13###
?nodelabels
?tiplabels
tiplabels(tr$tiplabel[4], 4, bg= "black", col= "white")
tiplabels(tr$tiplabel[11], Mus musculus, adj= 0, bg= "black", col= "white", font= 3)
tiplabels(tr$tiplabel[11], "Mus musculus", adj= 0, bg= "black", col= "white", font= 3)
tiplabels(tr$tiplabel[11], "Mus musculus", adj= 0, bg= "black", col= "white", font= 3)
tiplabels(tr$tiplabel[11], "Mus musculus", adj= 0, bg= "black", col= "white", font= 3)
dev.off()
plot (tr)
tiplabels(tr$tiplabel[11], 4, adj= 0, bg= "black", col= "white", font= 3)
tiplabels(tr$tiplabel[11], 11, adj= 0, bg= "black", col= "white", font= 3)
tiplabels(tr$tiplabel[4], 11, adj= 0, bg= "black", col= "white", font= 3)
dev.off()
plot (tr)
tiplabels(tr$tiplabel[4], 11, adj= 0, bg= "black", col= "white", font= 3)
tiplabels(tr$tiplabel[-4], 11, adj= 0, bg= "black", col= "white", font= 3)
dev.off()
plot (tr)
segments(10, 1, 10, 9, lwd= 2)
?segments
segments(0, 0, 100, 100, lwd= 2)
segments(0, 0, 100, 100, lwd= 10)
dev.off()
plot (tr)
segments(0, 0, 100, 100, lwd= 10)
segments(0, 0, 200, 200, lwd= 10)
dev.off
dev.off()
segments(0, 0, 200, 200, lwd= 10)
plot(tr)
savehistory(aunnomerindo.r)
savehistory("aunnomerindo.R")
